---
- name: Deploy to Kubernetes via SSH
  hosts: localhost
  vars:
    image_name: "johnberb/xyzrepo"   
    image_tag: "latest"               
    k8s_namespace: "default"      
    k8s_host: "docker@10.10.10.211"  

  tasks:
    - name: Apply Kubernetes deployment
      ansible.builtin.shell: |
        ssh {{ k8s_host }} "kubectl apply -f -" <<'EOF'
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: xyzrepo
          namespace: {{ k8s_namespace }}
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: xyzrepo
          template:
            metadata:
              labels:
                app: xyzrepo
            spec:
              containers:
              - name: xyzrepo
                image: {{ image_name }}:latest
                ports:
                - containerPort: 9090
        EOF
      args:
        executable: /bin/bash
      register: deploy_result
      changed_when: "'created' in deploy_result.stdout or 'configured' in deploy_result.stdout"

    - name: Verify deployment
      ansible.builtin.command: >
        ssh {{ k8s_host }}
        kubectl get deployment xyzrepo -n {{ k8s_namespace }} -o wide
      register: verify
      when: deploy_result is succeeded

    - name: Show deployment status
      ansible.builtin.debug:
        var: verify.stdout
      when: verify is defined